/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assignment;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Acer
 */
public class poststudent extends javax.swing.JFrame {

    /**
     * Creates new form poststudent
     */
    
    DBoparetion dbops=new DBoparetion();
    
    public poststudent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtLname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cbgender = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        txtnumber = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cbyear = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        cbmonth = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        sub11 = new javax.swing.JTextField();
        sub12 = new javax.swing.JTextField();
        sub14 = new javax.swing.JTextField();
        sub13 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        sub21 = new javax.swing.JTextField();
        sub22 = new javax.swing.JTextField();
        sub24 = new javax.swing.JTextField();
        sub23 = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        cbfacname = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtQulify = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        institute = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        YOC = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Post Student Registration");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 13, 243, 27));

        jLabel2.setText("First Name :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 97, -1));

        txtFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFnameActionPerformed(evt);
            }
        });
        jPanel1.add(txtFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 385, -1));

        jLabel3.setText("Last Name :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 97, -1));

        txtLname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLnameActionPerformed(evt);
            }
        });
        jPanel1.add(txtLname, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 385, -1));

        jLabel4.setText("Address :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 97, -1));

        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });
        jPanel1.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 385, -1));

        jLabel5.setText("Age :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 57, -1));

        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });
        jPanel1.add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 30, -1));

        jLabel6.setText("Gender :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 57, -1));

        cbgender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", " " }));
        cbgender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbgenderActionPerformed(evt);
            }
        });
        jPanel1.add(cbgender, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, -1));

        jLabel11.setText("Phone Number :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, -1, -1));

        txtnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumberActionPerformed(evt);
            }
        });
        jPanel1.add(txtnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, 97, -1));

        jLabel12.setText("Emai address :");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));
        jPanel1.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 285, -1));

        jLabel13.setText("Admission Year :");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 130, 101, -1));

        cbyear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040", " " }));
        jPanel1.add(cbyear, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 130, -1, -1));

        jLabel14.setText("Intake :");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 130, 49, -1));

        cbmonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "February", "July" }));
        cbmonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmonthActionPerformed(evt);
            }
        });
        jPanel1.add(cbmonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 130, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel15.setText("selected subjects");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 190, 124, -1));

        jLabel16.setText("1st semester");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 220, 80, -1));

        sub11.setText(" ");
        jPanel1.add(sub11, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 230, 110, -1));

        sub12.setText(" ");
        sub12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub12ActionPerformed(evt);
            }
        });
        jPanel1.add(sub12, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 230, 110, -1));

        sub14.setText(" ");
        sub14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub14ActionPerformed(evt);
            }
        });
        jPanel1.add(sub14, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 270, 110, -1));

        sub13.setText(" ");
        jPanel1.add(sub13, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 270, 110, -1));

        jLabel17.setText("2nd semester");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 330, -1, -1));

        sub21.setText(" ");
        jPanel1.add(sub21, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 330, 110, -1));

        sub22.setText(" ");
        jPanel1.add(sub22, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 330, 110, -1));

        sub24.setText(" ");
        sub24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub24ActionPerformed(evt);
            }
        });
        jPanel1.add(sub24, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 370, 110, -1));

        sub23.setText(" ");
        jPanel1.add(sub23, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 370, 110, -1));

        submit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        jPanel1.add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 460, 105, -1));

        cbfacname.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "School of Business", "School of Computing", "School of Engineering" }));
        jPanel1.add(cbfacname, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 90, 283, -1));

        jLabel18.setText("Faculty name");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 90, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Home");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 460, 93, -1));

        jLabel7.setText("Qulification type:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 107, -1));
        jPanel1.add(txtQulify, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 288, 55));

        jLabel8.setText("Institute:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 95, -1));
        jPanel1.add(institute, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 285, -1));

        jLabel9.setText("Year of completion:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 115, -1));
        jPanel1.add(YOC, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, 77, -1));

        jLabel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 550, 460));

        jLabel19.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, 430, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1091, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFnameActionPerformed

    private void txtLnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLnameActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void cbgenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbgenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbgenderActionPerformed

    private void txtnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumberActionPerformed

    private void cbmonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbmonthActionPerformed

    private void sub12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sub12ActionPerformed

    private void sub14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sub14ActionPerformed

    private void sub24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sub24ActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        poststudents addst=new poststudents();
        
        addst.setPstudent_id(0);
        addst.setFirst_name(txtFname.getText());
        addst.setLast_name(txtLname.getText());
        addst.setAge(new Integer(txtAge.getText()).intValue());
        addst.setGender(cbgender.getSelectedItem().toString());
        addst.setAddress(txtAddress.getText());
        addst.setPhone_number(new Integer(txtnumber.getText()).intValue());
        addst.setEmail(txtemail.getText());
        addst.setQulification(txtQulify.getText());
        addst.setInstitute(institute.getText());
        addst.setYOC(new Integer(YOC.getText()).intValue());
        addst.setAdmission_year(cbyear.getSelectedItem().hashCode());
        addst.setIntake_month(cbmonth.getSelectedItem().toString());
        addst.setCourse_sub1_1(sub11.getText());
        addst.setCourse_sub1_2(sub12.getText());
        addst.setCourse_sub1_3(sub13.getText());
        addst.setCourse_sub1_4(sub14.getText());
        addst.setCourse_sub2_1(sub21.getText());
        addst.setCourse_sub2_2(sub22.getText());
        addst.setCourse_sub2_3(sub23.getText());
        addst.setCourse_sub2_4(sub24.getText());
        addst.setFaculty_name(cbfacname.getSelectedItem().toString());

        if(dbops.addpoststudents(addst)){
            JOptionPane.showMessageDialog(this,"succesfuly inserted");
            clearfields();
        }else{
            JOptionPane.showMessageDialog(this,"not inserted");
            clearfields();
        }

        DBoparetion newstdn=new DBoparetion();
        newstdn.addpoststudents(addst);

    }//GEN-LAST:event_submitActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        mainform back=new mainform();
        back.setVisible(true);
        back.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(poststudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(poststudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(poststudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(poststudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new poststudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField YOC;
    private javax.swing.JComboBox<String> cbfacname;
    private javax.swing.JComboBox<String> cbgender;
    private javax.swing.JComboBox<String> cbmonth;
    private javax.swing.JComboBox<String> cbyear;
    private javax.swing.JTextField institute;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField sub11;
    private javax.swing.JTextField sub12;
    private javax.swing.JTextField sub13;
    private javax.swing.JTextField sub14;
    private javax.swing.JTextField sub21;
    private javax.swing.JTextField sub22;
    private javax.swing.JTextField sub23;
    private javax.swing.JTextField sub24;
    private javax.swing.JButton submit;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtLname;
    private javax.swing.JTextField txtQulify;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtnumber;
    // End of variables declaration//GEN-END:variables

    private void clearfields() {
    txtLname.setText("");
    txtFname.setText("");
    txtAddress.setText("");
    txtAge.setText("");
    txtnumber.setText("");
    txtemail.setText("");
    txtQulify.setText("");
    institute.setText("");
    YOC.setText("");
    sub11.setText("");
    sub12.setText("");
    sub13.setText("");
    sub14.setText("");
    sub21.setText("");
    sub22.setText("");
    sub23.setText("");
    sub24.setText("");
    }
}
